using System.Collections.Generic;
using System.IO;
using System.Text;
using Deeper.Character;
using Deeper.Upgrades;
using UnityEditor;
using UnityEngine;

namespace Deeper.EditorTools
{
    /// <summary>
    /// Writes <c>Docs/Engineering/03-UPGRADE_STATUS.md</c> — every authored upgrade and Curse, which
    /// pool it is actually in, and whether its effect runs.
    ///
    /// <b>Generated, never hand-written.</b> A typed inventory of forty-six entries is wrong the
    /// first time anyone edits an asset, and wrong silently — the same failure the two hand-
    /// maintained copies of the art fallback already had. This reads the assets and the pool assets
    /// themselves, so the document cannot claim something the project does not contain.
    ///
    /// It reports <b>pool membership as wired</b>, not as intended: an entry appears under "shared"
    /// because it is in the shared pool's array, not because <see cref="UpgradeCatalog"/> says it
    /// should be. That is what makes this an audit rather than a second copy of the table.
    /// </summary>
    public static class UpgradeStatusReport
    {
        private const string UpgradeFolder = "Assets/_Main/Data/Upgrades";
        private const string CurseFolder = "Assets/_Main/Data/Curses";
        private const string WeaponFolder = "Assets/_Main/Data/Weapons";
        private const string OutputPath = "Assets/_Main/Docs/Engineering/03-UPGRADE_STATUS.md";

        [MenuItem("Deeper/Report Upgrade Status")]
        public static void Report()
        {
            List<UpgradeDefinition> upgrades = Load<UpgradeDefinition>(UpgradeFolder);
            List<CurseDefinition> curses = Load<CurseDefinition>(CurseFolder);
            List<UpgradePool> pools = Load<UpgradePool>(UpgradeFolder);
            List<CursePool> cursePools = Load<CursePool>(CurseFolder);
            List<WeaponDefinition> weapons = Load<WeaponDefinition>(WeaponFolder);

            // Where each upgrade is actually drawn from, read off the pool assets.
            var membership = new Dictionary<UpgradeDefinition, string>();

            for (int i = 0; i < pools.Count; i++)
            {
                IReadOnlyList<UpgradeDefinition> shared = pools[i].Shared;
                for (int e = 0; e < shared.Count; e++) Claim(membership, shared[e], "Shared");
            }

            for (int i = 0; i < weapons.Count; i++)
            {
                UpgradeDefinition[] sub = weapons[i].WeaponUpgrades;
                if (sub == null) continue;

                for (int e = 0; e < sub.Length; e++) Claim(membership, sub[e], weapons[i].DisplayName);

                // A weapon's Relic is authored on the weapon, not in a pool, and is handed over by
                // guaranteed drop only — so it is placed, not orphaned.
                Claim(membership, weapons[i].Relic.Offer, weapons[i].DisplayName + " relic");
            }

            var sb = new StringBuilder();
            Header(sb, upgrades, curses, membership);

            Section(sb, "Shared pool", upgrades, membership, "Shared");

            for (int i = 0; i < weapons.Count; i++)
            {
                Section(sb, weapons[i].DisplayName + " sub-pool", upgrades, membership, weapons[i].DisplayName);
                Section(sb, weapons[i].DisplayName + " relic", upgrades, membership, weapons[i].DisplayName + " relic");
            }

            Section(sb, "In no pool", upgrades, membership, null);
            Curses(sb, curses, cursePools);
            Weights(sb, pools);

            Directory.CreateDirectory(Path.GetDirectoryName(OutputPath));
            File.WriteAllText(OutputPath, sb.ToString());
            AssetDatabase.ImportAsset(OutputPath);

            Debug.Log("Wrote " + OutputPath + " — " + upgrades.Count + " upgrades, " +
                      curses.Count + " Curses.");
        }

        // ---------------------------------------------------------------- sections

        private static void Header(StringBuilder sb, List<UpgradeDefinition> upgrades,
                                   List<CurseDefinition> curses,
                                   Dictionary<UpgradeDefinition, string> membership)
        {
            int live = 0, noIcon = 0, orphans = 0;

            for (int i = 0; i < upgrades.Count; i++)
            {
                if (Runs(upgrades[i])) live++;
                if (upgrades[i].Icon == null) noIcon++;
                if (!membership.ContainsKey(upgrades[i])) orphans++;
            }

            for (int i = 0; i < curses.Count; i++)
            {
                if (curses[i].Icon == null) noIcon++;
            }

            sb.AppendLine("# UPGRADE STATUS — what is authored, and what actually runs");
            sb.AppendLine();
            sb.AppendLine("**Generated by `Deeper/Report Upgrade Status`. Do not edit by hand — re-run it.**");
            sb.AppendLine();
            sb.AppendLine("Read from the assets and the pool assets themselves, so it reports what the project");
            sb.AppendLine("*contains* rather than what any table says it should. Names, tiers and values come from");
            sb.AppendLine("`Design/03-CONTENT_DESIGN.md` §1-§4 and `Design/04-BALANCE.md` §9-§12; divergences are");
            sb.AppendLine("recorded in `Docs/00-DESIGN_CHANGE_BRIEF.md` §23.");
            sb.AppendLine();
            sb.Append("- **").Append(upgrades.Count).Append(" upgrades** and **")
              .Append(curses.Count).AppendLine(" Curses** authored.");
            sb.Append("- **").Append(live).Append(" of ").Append(upgrades.Count)
              .AppendLine(" upgrades have a working effect.** The rest are data only.");
            sb.Append("- ").Append(noIcon == 0 ? "Every entry has an icon." : noIcon + " entries have NO icon.")
              .AppendLine();

            if (orphans > 0)
            {
                sb.Append("- ⚠️ **").Append(orphans)
                  .AppendLine(" upgrades are in no pool and on no weapon** — see the last table.");
            }

            sb.AppendLine();
            sb.AppendLine("## What \"runs\" means");
            sb.AppendLine();
            sb.AppendLine("**Derived from whether the asset carries `StatModifier`s**, which is exactly what");
            sb.AppendLine("`RunUpgrades.Add` applies through `PlayerStats`. Everything else — a damage-over-time, a");
            sb.AppendLine("proc, a dash that deals damage, every Curse — needs a hook in the damage pipeline that");
            sb.AppendLine("does not exist yet, and is authored with a real name, description, tier and icon that");
            sb.AppendLine("changes no number. That is the second half of Milestone 4.");
            sb.AppendLine();
            sb.AppendLine("⚠️ **This check will need to learn about those hooks when they land**, or it will start");
            sb.AppendLine("reporting a working behavioural upgrade as data-only.");
            sb.AppendLine();
        }

        private static void Section(StringBuilder sb, string title, List<UpgradeDefinition> upgrades,
                                    Dictionary<UpgradeDefinition, string> membership, string pool)
        {
            var rows = new List<UpgradeDefinition>();

            for (int i = 0; i < upgrades.Count; i++)
            {
                string found;
                bool has = membership.TryGetValue(upgrades[i], out found);

                if (pool == null ? !has : (has && found == pool)) rows.Add(upgrades[i]);
            }

            if (rows.Count == 0) return;

            sb.Append("## ").Append(title).Append(" — ").Append(rows.Count)
              .AppendLine(rows.Count == 1 ? " entry" : " entries");
            sb.AppendLine();

            if (pool == null)
            {
                sb.AppendLine("**In no pool and on no weapon.** Authored but unreachable: nothing can ever offer");
                sb.AppendLine("these. Either add them to a pool or delete them.");
                sb.AppendLine();
            }

            // Category is the icon-led card's effect taxonomy (EffectSummary.Category), not this
            // table's own idea — printed here so a mistagged entry (one left at the enum's default,
            // Health) is something a reader can actually spot rather than a value locked in code.
            sb.AppendLine("| Upgrade | Tier | Category | Effect | Runs | Notes |");
            sb.AppendLine("|---|---|---|---|---|---|");

            for (int i = 0; i < rows.Count; i++)
            {
                UpgradeDefinition u = rows[i];

                sb.Append("| ").Append(u.DisplayName)
                  .Append(" | ").Append(u.Tier)
                  .Append(" | ").Append(u.Summary.Category)
                  .Append(" | ").Append(Clean(u.Description))
                  .Append(" | ").Append(Runs(u) ? "yes" : "no")
                  .Append(" | ").Append(Notes(u))
                  .AppendLine(" |");
            }

            sb.AppendLine();
        }

        private static void Curses(StringBuilder sb, List<CurseDefinition> curses, List<CursePool> pools)
        {
            var pooled = new HashSet<CurseDefinition>();

            for (int i = 0; i < pools.Count; i++)
            {
                IReadOnlyList<CurseDefinition> entries = pools[i].Entries;
                for (int e = 0; e < entries.Count; e++) pooled.Add(entries[e]);
            }

            sb.Append("## Curses — ").Append(curses.Count)
              .AppendLine(curses.Count == 1 ? " entry" : " entries");
            sb.AppendLine();
            sb.AppendLine("Drawn from their own pool at a flat uniform weight (BALANCE §13), into the offer's");
            sb.AppendLine("always-visible 4th slot. **None of them runs** — every Curse in CONTENT_DESIGN §3 is");
            sb.AppendLine("behavioural, so a run can currently take one and receive neither half of the trade.");
            sb.AppendLine();
            sb.AppendLine("| Curse | Category | Upside | Cost | In pool |");
            sb.AppendLine("|---|---|---|---|---|");

            for (int i = 0; i < curses.Count; i++)
            {
                CurseDefinition c = curses[i];

                sb.Append("| ").Append(c.DisplayName)
                  .Append(" | ").Append(c.UpsideSummary.Category)
                  .Append(" | ").Append(Clean(c.Upside))
                  .Append(" | ").Append(Clean(c.Downside))
                  .Append(" | ").Append(pooled.Contains(c) ? "yes" : "**NO**")
                  .AppendLine(" |");
            }

            sb.AppendLine();
        }

        private static void Weights(StringBuilder sb, List<UpgradePool> pools)
        {
            if (pools.Count == 0) return;

            sb.AppendLine("## Draw weights (BALANCE §13)");
            sb.AppendLine();
            sb.AppendLine("One weighted draw across the shared pool plus the equipped weapon's sub-pool, **not");
            sb.AppendLine("tier-gated** — a Common, a Rare and an Epic can appear in the same offer. The draw picks");
            sb.AppendLine("a tier by weight and then an entry uniformly inside it, so these percentages hold no");
            sb.AppendLine("matter how many entries a tier happens to hold. Legendary is excluded entirely.");
            sb.AppendLine();
            sb.AppendLine("| Biome | Common | Rare | Epic |");
            sb.AppendLine("|---|---|---|---|");

            string[] names = { "1 Upper Caves", "2 Flooded Tunnels", "3 Molten Depths" };

            for (int b = 0; b < names.Length; b++)
            {
                UpgradePool.TierWeights w = pools[0].WeightsFor(b + 1);

                sb.Append("| ").Append(names[b])
                  .Append(" | ").Append(w.Common)
                  .Append(" | ").Append(w.Rare)
                  .Append(" | ").Append(w.Epic)
                  .AppendLine(" |");
            }

            sb.AppendLine();
        }

        // ---------------------------------------------------------------- helpers

        /// <summary>Whether taking this upgrade changes a number today.</summary>
        private static bool Runs(UpgradeDefinition upgrade)
        {
            return upgrade.Modifiers != null && upgrade.Modifiers.Length > 0;
        }

        private static string Notes(UpgradeDefinition upgrade)
        {
            var parts = new List<string>();

            if (upgrade.Icon == null) parts.Add("**no icon**");
            if (upgrade.Requires != null) parts.Add("requires " + upgrade.Requires.DisplayName);

            UpgradeDefinition[] excludes = upgrade.Excludes;
            if (excludes != null)
            {
                for (int i = 0; i < excludes.Length; i++)
                {
                    if (excludes[i] != null) parts.Add("excludes " + excludes[i].DisplayName);
                }
            }

            if (upgrade.Tier == UpgradeTier.Legendary) parts.Add("never in a normal draw");

            return parts.Count == 0 ? "" : string.Join(", ", parts.ToArray());
        }

        /// <summary>A pipe in a description would split the markdown table cell it sits in.</summary>
        private static string Clean(string text)
        {
            if (string.IsNullOrEmpty(text)) return "";

            return text.Replace("|", "/").Replace("\r", " ").Replace("\n", " ").Trim();
        }

        private static void Claim(Dictionary<UpgradeDefinition, string> membership,
                                  UpgradeDefinition upgrade, string pool)
        {
            if (upgrade == null || membership.ContainsKey(upgrade)) return;

            membership[upgrade] = pool;
        }

        private static List<T> Load<T>(string folder) where T : Object
        {
            var found = new List<T>();
            string[] guids = AssetDatabase.FindAssets("t:" + typeof(T).Name, new[] { folder });

            for (int i = 0; i < guids.Length; i++)
            {
                var asset = AssetDatabase.LoadAssetAtPath<T>(AssetDatabase.GUIDToAssetPath(guids[i]));
                if (asset != null) found.Add(asset);
            }

            return found;
        }
    }
}
